version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: display env
          command: |
              echo pwd=`pwd`
              ls -alh
      - run:
          name: deploy script
          command: |
              cp ./script/server.js .
              cp ./script/upload-script.sh .
              ./upload-script.sh
      - run:
          name: delete old fleet
          command: |
              cp ./script/delete-old-fleet.sh .
              ./delete-old-fleet.sh
