version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: display env
          command: |
              echo pwd=`pwd`
              ls -alh
      - run:
          name: deploy script
          command: |
              cp ./script/server.js .
              cp ./script/upload-script.sh .
              #./upload-script.sh
      - run:
          name: wait for fleet
          command: |
              cp ./script/wait-for-fleet.sh .
              #./wait-for-fleet.sh
      - run:
          name: update alias
          command: |
              cp ./script/update-alias.sh .
              #./update-alias.sh
      - run:
          name: delete inactive fleet
          command: |
              cp ./script/delete-old-fleet.sh .
              ./delete-old-fleet.sh
