version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - deploy:
          name: deploy
          command: awscli --version
