version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: deploy script
          command: |
              cp script/VERSION .
              cp script/server.js .
              cp script/upload-script.sh
              ./upload-script.sh
